$(call lib,../../src/libnametag):
	$(MAKE) -C $(dir $@) $(notdir $@)

$(call lib,../../src/libnametag.dyn):
	$(MAKE) -C $(dir $@) $(notdir $@)

$(call lib,../../morphodita/src/libmorphodita):
	$(MAKE) -C $(dir $@) $(notdir $@)

$(call lib,../../morphodita/src/libmorphodita.dyn):
	$(MAKE) -C $(dir $@) $(notdir $@)

.PHONY: veryclean
veryclean: clean
	$(MAKE) -C ../../src veryclean
